repos:
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.9
    hooks:
    -   id: uv-lock

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/gitleaks/gitleaks
    rev: "v8.28.0"
    hooks:
    -   id: gitleaks

-   repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
    -   id: bandit

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.8"
    hooks:
    -   id: ruff-format
    -   id: ruff-check
        args:
        -   "--exit-non-zero-on-fix"

-   repo: https://github.com/pycqa/pylint
    rev: "v3.3.8"
    hooks:
    -   id: pylint
        additional_dependencies:
        -   "google-cloud-firestore==2.18.0"
        -   "pydantic==2.9.2"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.1"
    hooks:
    -   id: mypy
        exclude: ^app/views/templates/books
        additional_dependencies:
        -   "pydantic==2.9.2"
        -   "pyyaml==6.0.2"

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.22.0"
    hooks:
    -   id: commitlint
        stages:
        -   commit-msg
        additional_dependencies:
        -   "@commitlint/config-conventional"
        args:
        -   "--config=.commitlintrc.json"
