name: Lint and Test Workflow

on:
  push:
    branches:
      - master

  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.9"

    - name: Install Dependencies
      run: |
        uv python install
        uv sync --group lint

    - name: Run Linter
      run: |
        uv run --frozen --no-sync poe format

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.9"

    - name: Install Dependencies
      run: |
        uv python install
        uv sync --group test

    - name: Run Tests
      run: |
        uv run --frozen --no-sync poe test

    - name: Check Coverage
      run: |
        uv run --frozen --no-sync poe check-coverage
