name: Deploy to Render

on:
  workflow_run:
    workflows:
      - Lint and Test
    branches: master
    types: completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deployment
      uses: sws2apps/render-deployment@v1.8.0
      with:
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_API_KEY }}
        multipleDeployment: false
